version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
