name: OSV Dependency Scanner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  osv-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google/osv-scanner-action@v2
        with:
          scan-args: |-
            --config .osv-scanner.toml
          upload-sarif: true
      - name: PR Scan
        if: github.event_name == 'pull_request'
        uses: google/osv-scanner-action@v2
        with:
          scan-args: |
            --config .osv-scanner.toml
