name: PSScriptAnalyzer PowerShell Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  psscriptanalyzer:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@4c68ce7e4ab4fdaafd03b50b961ffd06c65b5db7  # v1.1
        with:
          path: .\
          recurse: true
          output: results.sarif
          settings: CodeFormatting

      - name: Upload PSScriptAnalyzer results
        uses: github/codeql-action/upload-sarif@c7d0eebf0efb81753d773b54ee46f4278db8ab5d  # v3.25.12
        with:
          sarif_file: results.sarif
