name: OpenSSF Scorecard
on:
  # Run on branch protection changes, releases, and schedule
  branch_protection_rule:
  release:
    types: [published]
  schedule:
    # Weekly on Saturdays at 00:00 UTC
    - cron: '0 0 * * 6'
  push:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard
      security-events: write
      # Needed to publish results and get a badge
      id-token: write
      # Required to read repository content
      contents: read
      # Required to read Actions workflows
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          # Publish the results for public repos to enable the badge
          publish_results: true

      # Upload the results as artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      # Upload the results to GitHub's code scanning dashboard
      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
